### ISSUE TITLE
Deploy task fails on a new WebCTRL 8.0 install

### ISSUE THREAD

**Issue by MxD-js** [automatic-controls/webctrl-addon-dev#1]
On a fresh install of WC8.0 deploy functionality fails since the script cannot find the path, the "addon" folder in root of WebCTRL install directory is not present if no addons are installed, creating the folder manually OR installing an addon will create this folder, then deploy task runs fine.

**Comment by cvogt729** [comment]
The latest commit should fix this issue. Thanks for the feedback!
